Models/GradeCalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment2.Models
{
    public class GradeCalculatorModel
    {
        [Required]
        [Range(0,100)]
        public double assignment { get; set; }

        [Required]
        [Range(0, 100)]
        public double project { get; set; }

        [Required]
        [Range(0, 100)]
        public double quiz { get; set; }

        [Required]
        [Range(0, 100)]
        public double exam { get; set; }

        [Required]
        [Range(0, 100)]
        public double intex { get; set; }
    }
}

Controllers/NewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assignment2.Models;
using Microsoft.AspNetCore.Mvc;

namespace Assignment2.Controllers
{
    public class NewController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("GradeCalculator")]
        public IActionResult GradeCalculator()
        {
            return View();
        }

        [HttpPost("GradeCalculator")]
        public IActionResult GradeCalculator(GradeCalculatorModel model)
        {
            return View();
        }
    }
}

Views/New/GradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Calculator";
    ViewBag.Header = "Grade Calculator";
}

@model Assignment2.Models.GradeCalculatorModel

<body>

    <p>Please use the following inputs to calculate your final grade in IS 413.</p>


    <!--Form alternative method-->
    <form method="post">
        <br>
        <label for="assignment">Average Assignment Grade:</label>
        <input asp-for="assignment" id="assignment" />
        <br><br>
        <label for="project">Average Project Grade:</label>
        <input asp-for="project" id="project" />
        <br><br>
        <label for="quiz">Average Quiz Grade:</label>
        <input asp-for="quiz" id="quiz" />
        <br><br>
        <label for="exam">Average Exam Grade:</label>
        <input asp-for="exam" id="exam" />
        <br><br>
        <label for="intex">Intex Grade:</label>
        <input asp-for="intex" id="intex" />
        <br><br>

        <input type="submit" value="Calculate" id="submitButton" />

        <div asp-validation-summary="All"></div>
    </form>










    <!--html inputs-->

    <!--
    <br>
    <label for="assignment">Average Assignment Grade:</label>
    <input name="assignment" id="assignment" />
    <br><br>
    <label for="project">Average Project Grade:</label>
    <input name="project" id="project" />
    <br><br>
    <label for="quiz">Average Quiz Grade:</label>
    <input name="quiz" id="quiz" />
    <br><br>
    <label for="exam">Average Exam Grade:</label>
    <input name="exam" id="exam" />
    <br><br>
    <label for="intex">Intex Grade:</label>
    <input name="intex" id="intex" />

    <br><br>
    <button onclick="calcGrade()">View Final Score</button>
    -->



    



    <!--Output-->
    <p id="outputGrade"></p>

</body>

Views/New/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Home";
    ViewBag.Header = "Welcome!";
}


<body>

    <br>

        <br>
        <img src="img/harp.JPG">
        <br><br>

        <p>I am hoping to get a firm grasp on the C# language. I am going to use the language for several personal projects, so I hope to become an expert in it.</p>
        <br>
        <p>The following are the top 3 jobs that I am interested in pursuing.</p>

        <div>
            <ol>
                <li>Software Development</li>
                <li>Cybersecurity</li>
                <li>Data Analyst</li>
            </ol>
        </div>

        <br><br>

        

    <br>

</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link rel="icon" href="~/img/QuinnSmall.jpg">
    <link rel="stylesheet" href="~/css/main.css">
</head>
<body>

    <!--Layout div with all styling-->
    <br>
    <div class="mainDiv">
        <header>
            <h1>@ViewBag.Header</h1>
            <menu>
                <ul>
                    <li><a asp-controller="New" asp-action="Index">Home</a></li>
                    <li><a asp-controller="New" asp-action="GradeCalculator">Grade Calculator</a></li>
                </ul>
            </menu>
        </header>

        @RenderBody()

    </div>
    <br>


    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/js/function.js"></script>
</body>
</html>